# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 19:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_auto_20170613_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='likers',
            field=models.ManyToManyField(related_name='liked_tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
